### ISSUE TITLE
Фидбек

### ISSUE THREAD

**Issue by karpp** [tigran-edu/Intro-to-System-Design#1]
Все супер, все работает. Круто что проставил зависимости в docker-compose. Только зачем два раза uuid склеивать?... Одного достаточно... Энивей ставлю 10!

Из того, что можно было бы улучшить:
* у каждого инстанса открыты порты, это не очень хорошо, лучше было бы оставить только nginx
* в сборке сервиса в Dockerfile лучше сначала устанавливать зависимости, а потом копировать файлы с кодом. Это делается потому что при повторной сборке докер берет из кэша шаги, которые не менялись. Но если ты поменяешь код, то этот шаг и все последующие (pip install в твоем случае) будут запущены заново, будет занимать больше времени

**Comment by YaTigran** [comment]
Спасибо за подсказку с докером!
